### ISSUE TITLE
How to run command on gpu 

### ISSUE THREAD

**Issue by 9Joker** [TCNOco/TcNo-TCHT#12]
I have RTX 3060 Laptop GPU. Can it run in this Device, How to fix it. 
![image](https://github.com/TCNOco/TcNo-TCHT/assets/114092257/1bd5ebf2-7c5c-49a2-a2d9-3354e8212182)

**Comment by TCNOco** [comment]
You need CUDA and cuDNN installed. I am working on automating this as we speak :)

**Comment by TCNOco** [comment]
I have released an update to address this issue. Not only was some software missing on some users computers, which the script now auto-installs as well, the launch arguments were wrong. `--gpu` was used (and worked for me) instead of `--gpu-vendor nvidia`.

Please run the install script again for changes to take place :) `iex (irm roop.tc.ht)`
