### ISSUE TITLE
Install directory appears hard-coded

### ISSUE THREAD

**Issue by dsl101** [TCNOco/TcNo-TCHT#4]
Nothing is installed to the newly created folder (at odds with [this video](https://www.youtube.com/watch?v=d4dk_7FptXk)). The script appears to have `C:\TCHT\oobabooga_windows` hardcoded in various places, making it impossible to install to the desired location...

**Comment by TCNOco** [comment]
I had to change how it worked because they day after posting the video, the oobabooga developers changed how it worked entirely... And it has major issues running in paths with a space, and so on. Having it in one place makes it much easier to install multiple models and the rest using the powershell scripts.

I have since changed it to use an environment variable instead.

All paths should be 
```
$TCHT = [Environment]::GetEnvironmentVariable("TC.HT", "Machine")
$TCHT\oobabooga_windows`
```
A mildly better solution.

Start > Environment Variables:
![image](https://user-images.githubusercontent.com/10319195/233603721-ba464eba-bc3c-478f-87cd-e1bd197a2338.png)

Edit Environment Variables

![image](https://user-images.githubusercontent.com/10319195/233603775-c62875f7-67be-4ea4-8003-bac84c270cf9.png)

New System variable
![image](https://user-images.githubusercontent.com/10319195/233603814-247e38ac-61da-4fff-94be-0792f5913604.png)

Set custom path
![image](https://user-images.githubusercontent.com/10319195/233603899-185de9af-4385-4cf4-a294-3945d72308d7.png)

I will close this as it should be solved, but scripts are always open to improvement :)

**Comment by TCNOco** [comment]
I've wanted to install them in a set user/machine location so an uninstall script, updater and the rest can be built out in the future. For example, people always ask "HOW UNINSTL!?!" and the answer ranged in difficulty depending on what they did. A simple uninstaller that gives them options based on the detected ""installations"" is super easy.

However, these aren't truly ""installed"". They are just downloaded, and shortcuts made.

I forget the exact reasoning. It was best with just cd/Set-Location, and it worked. With an update to Ooba, there was a reason I HAD to do it with set paths, but I can't recall. Spaces in the folder path led to a lot of issues with Miniconda, and less tech-savvy people don't really get why it doesn't work. I try to keep as simple as possible for those who aren't used to the command line.

Using the user's home folder would be useful, but I think Microsoft accounts use your name/surname and can have a space... so it was a machine-wide "install" I settled on.

Ultimately the script is workaround on workaround, as I am not involved with the development of projects this 'installer' repo uses.

**Comment by dsl101** [comment]
Yeah, totally understand. For me, the issue was that c:\ did not have enough space, but any of the other 5 drives did, I just couldn't get it to go there :). It's a lot of hassle I know to add more and more features. Even just passing the path as a command line parameter might be better though, and could be checked for spaces?

**Comment by TCNOco** [comment]
Absolutely. Fast NVMe SSDs are expensive, so only Windows and maybe a game or two... not 250GB for a Stable Diffusion install.

Now, making this cross-platform, I don't think environment variables are the way to do it... I'm not sure the best way to proceed.

Maybe store the install path in `C:\tcht.txt` or something, linux `~/tcht.txt`. First script that installs something says 
```
AI can take a LOT of space over time.
Do you want TCHT programs to install to `C:\TCHT`?
Type a path, or leave blank for the default now: 
```

**Comment by TCNOco** [comment]
You are correct. It was a rushed fix to a problem lots of people were having, I didn't have much time, with many people complaining. It fixed the majority of complaints as a band aid fix.

I plan on implementing this approach within a day or two, I don't have good internet at the moment. 

Pick where to install:
- (default) C:/TCHT: Hit enter, or 1 and enter. 
- Current folder (): Hit 2 and enter.
- Enter a custom path and hit enter.

That will then be saved into the environment variables for recall later.

**Comment by TCNOco** [comment]
I have updated the scripts. Please run one of the following to check the new functionality :) I have not had the time to fully test it being stuck to a Mac for a few days, but from remote testing it seems to work as expected.

`iex (irm vicuna.tc.ht)`
`iex (irm ooba.tc.ht)`
`iex (irm oasst.tc.ht)`

**Comment by dsl101** [comment]
Hmm. Not very reassuring, and pressing Enter just repeats the warning :(

![image](https://user-images.githubusercontent.com/900542/235128204-a41bec81-b330-4a11-9d45-c27a370c8182.png)

I think it's warning about admin? But for some reason the text doesn't show up for me. If I copy the contents to a plain text editor, I can see the warning.

Anyway, I reran in an admin powershell (version 7 in fact, which seems to be working now, see [my other issue](#3), did you fix that too?) and all is installing OK.

**Comment by TCNOco** [comment]
Yes, powershell needs to be run as admin.
